[Icon Theme]
Name=Adwair
Comment=A refined WhiteSur icon theme blending its polished look with the clean, native feel of Adwaita.
Inherits=Adwaita,AdwaitaLegacy,hicolor,breeze
Example=folder
FollowsColorScheme=true
KDE-Extensions=.svg

Directories=actions/symbolic,apps/scalable,apps/symbolic,categories/32,categories/symbolic,devices/scalable,devices/symbolic,legacy/symbolic,mimetypes/scalable,mimetypes/symbolic,places/scalable,places/symbolic,status/scalable,status/symbolic,ui/symbolic

[actions/symbolic]
Size=16
Context=Actions
Type=Scalable
MinSize=16
MaxSize=512

[apps/scalable]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[apps/symbolic]
Size=16
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[categories/32]
Size=32
Context=Categories
Type=Scalable
MinSize=32
MaxSize=512

[categories/symbolic]
Size=16
Context=Categories
Type=Scalable
MinSize=16
MaxSize=512

[devices/scalable]
Size=64
Context=Devices
Type=Scalable
MinSize=32
MaxSize=512

[devices/symbolic]
Size=16
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512

[legacy/symbolic]
Size=16
Context=Legacy
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/scalable]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=512

[mimetypes/symbolic]
Size=16
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[places/scalable]
Size=96
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[places/symbolic]
Size=16
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[status/scalable]
Size=64
Context=Status
Type=Scalable
MinSize=16
MaxSize=512

[status/symbolic]
Size=16
Context=Status
Type=Scalable
MinSize=16
MaxSize=512

[ui/symbolic]
Size=16
Context=UI
Type=Scalable
MinSize=16
MaxSize=512
